### PR TITLE
Potion Improvements, Unknown Class Card Fixes & More

### PR DESCRIPTION
**Pull request by JamesTripleQ**
Potions:
- Added potion outlines for Automaton, Collector & Gremlins,
- Added many tooltips to various potions,
- Removed the "Technique" tooltip from Bottled Technique as it was pointless,
- Tweaked some potion descriptions to be more in line with the rest of the game.

Unknown Class Cards:
- Added a proper texture to the Collector's unknown card,
- Fixed some of the unknown card banners not loading due to using outdated Enums (Automaton, Champ & Hexaghost),
- Removed the unknown class card for Collectibles since it couldn't spawn anyway.

Misc:
- Fixed Hermit's character select button being pixelated on its edges,
- Tweaked a few Collector strings,
- Added `[REMOVE_SPACE]` in a few places to avoid highlighted parenthesis.

### CODE REVIEW

**Comment by Mwallx** [comment]
There's some related issue to potion tooltips for other languages, like if it fails(it fails even when it shouldnt, it's a bug) to locate a keyword it would throw an exception resulting the potion to be a fire potion.

**Comment by JamesTripleQ** [comment]
I will test that yes tho note that I used the same system used by other vanilla potions for vanilla keywords and other downfall potions for modded keywords.

**Comment by JamesTripleQ** [comment]
> There's some related issue to potion tooltips for other languages, like if it fails(it fails even when it shouldnt, it's a bug) to locate a keyword it would throw an exception resulting the potion to be a fire potion. Could you try launch the game in any language downfall supports and check if there are many fire potions? thanks

Tested French and got no issues. I did however also test it with Simplified Chinese and some potions did break/disappear though I don't think all of them were the ones I edited. Lmk if there's anything I can do.

Btw a broken potion is replaced by a Fire Potion only if it's common, if it's any other rarity it will just get deleted... I know because when adding the tooltips I made a mistake which caused that but I went back, fixed it and made sure every potion loaded correctly.

**Comment by Mwallx** [comment]
> > There's some related issue to potion tooltips for other languages, like if it fails(it fails even when it shouldnt, it's a bug) to locate a keyword it would throw an exception resulting the potion to be a fire potion. Could you try launch the game in any language downfall supports and check if there are many fire potions? thanks
> 
> Tested French and got no issues. I did however also test it with Simplified Chinese and some potions did break/disappear though I don't think all of them were the ones I edited. Lmk if there's anything I can do.
> 
> Btw a broken potion is replaced by a Fire Potion only if it's common, if it's any other rarity it will just get deleted... I know because when adding the tooltips I made a mistake which caused that but I went back, fixed it and made sure every potion loaded correctly.

I think it was not diappearing but listed into common since fire potions are common. So if you see any other fire potion in the common potions they are bugged. That said I already know how to let the potions work properly, not by fixing the bug but if you put those related keywords into each language's keywords.json so that they are the first alias to be searched, it would become okay, you can see many keywords are having this format because I told those localizers to do so to prevent that bug. So if you understand what I'm saying please fix them by the way, could you? Thanks for you contribution, it's not often we receive random PRs lol.

**Comment by JamesTripleQ** [comment]
> So if you understand what I'm saying please fix them by the way, would you?

If I understood correctly I should go through the various non-english `KeywordStrings.json` files and add the contets of `NAMES` from the english file to the `NAMES` of the translated one right? Looking at some of the existing files it doesn't look like they need to be the first entry in that list.

**Comment by Mwallx** [comment]
> > So if you understand what I'm saying please fix them by the way, would you?
> 
> If I understood correctly I should go through the various non-english `KeywordStrings.json` files and add the contets of `NAMES` from the english file to the `NAMES` of the translated one right? Looking at some of the existing files it doesn't look like they need to be the first entry in that list.

Well you might be using a different way calling those keywords so the situation might be different, but in my fix we only need to put a single English keyword(the called one) before the localized ones then it'd work(due to unknown reason).

**Comment by JamesTripleQ** [comment]
I see, I was looking at some of the localized keyword files and they just put everything in there.

**Comment by JamesTripleQ** [comment]
So I checked out what needed to be done and, as much as I'd love to help with this, this is probably a task best reserved for the translators. I noticed that in some cases keywords don't load because they don't have the english name in `NAMES` but in other cases it's because the keyword translation is missing entirely. There's also the fact that this doesn't just affect potions but keywords in general and as such I'm not too confident in messing around with that. Sorry.

**Comment by mikemayhemdev** [comment]
A new contributor, how exciting! I see the conversation here - I'm reluctant to merge this in until it's fully operational in all languages. Unfortunately that's somewhat of a requirement for operating in Downfall, that all languages are still launchable. STS is very easy to crash if anything changes with the loc jsons. It doesn't matter if the strings are in English or machine-translated, but the game does have to be able to launch.

**Comment by Mwallx** [comment]
> So I checked out what needed to be done and, as much as I'd love to help with this, this is probably a task best reserved for the translators. I noticed that in some cases keywords don't load because they don't have the english name in `NAMES` but in other cases it's because the keyword translation is missing entirely. There's also the fact that this doesn't just affect potions but keywords in general and as such I'm not too confident in messing around with that. Sorry.

Okay I pulled your changes and fixed them in my PR, don't be misunderstood if this gets closed, thanks.

**Comment by JamesTripleQ** [comment]
> Unfortunately that's somewhat of a requirement for operating in Downfall, that all languages are still launchable.

Ah I see, makes sense, I wasn't sure of this though since I noticed that many languages are missing many keywords. And I don't mean that they're there but not translated, some of them straight up aren't present in the files. Korean I think, for example, has some potions that don't load regardless of my changes.

> Okay I pulled your changes and fixed them in my PR, don't be misunderstood if this gets closed, thanks.

Don't worry, I'm just happy to help. As you've probably noticed I'm someone who likes that additional bit of polish & consistency in mods so I might make a few more PRs in the future if I get the chance. For example, I really wanted to fix some of the Collectible images being the wrong type however, while I can convert Skills to Attacks and Attacks to Powers, I can't do viceversa without the source image files.

**Pull request merged**
